package open.cklan.com.compile.processor;

import com.example.Schema;
import com.google.auto.common.MoreElements;
import com.google.auto.service.AutoService;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import org.apache.commons.collections4.CollectionUtils;

import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;

import open.cklan.com.compile.util.Consts;
import open.cklan.com.compile.util.Logger;

@AutoService(Processor.class)
@SupportedSourceVersion(SourceVersion.RELEASE_7)
public class SchemaProcessor extends AbstractProcessor{
    Logger logger;
    Filer filer;
    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        logger=new Logger(processingEnv.getMessager());
        filer=processingEnv.getFiler();
        logger.info("SchemaProcessor init");
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        Set<String> supportAnnotationTypes=new LinkedHashSet<>();
        supportAnnotationTypes.add(Schema.class.getName());
        return supportAnnotationTypes;
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        logger.info("解析schema注解");
        if(!CollectionUtils.isEmpty(annotations)){
            handleSchema(roundEnv);
            logger.info("结束我的表演");
            return true;
        }
        return false;
    }

    private void handleSchema(RoundEnvironment roundEnv) {
        Set<? extends Element> schemaElements = roundEnv.getElementsAnnotatedWith(Schema.class);
        if(!CollectionUtils.isEmpty(schemaElements)){
            try {
                TypeSpec.Builder typeBuilder=TypeSpec.classBuilder(Consts.SCHEMA_HELPER_NAME)
                        .addModifiers(Modifier.PUBLIC)
                        .addJavadoc("Generated by $S",this.getClass().getSimpleName());
                MethodSpec.Builder methodBuilder=MethodSpec.constructorBuilder()
                        .addModifiers(Modifier.PUBLIC)
                        .addModifiers(Modifier.FINAL)
                        .addModifiers(Modifier.STATIC);

                for (Element element :schemaElements) {
                    if(element.getKind()== ElementKind.CLASS){
                        TypeMirror typeMirror = element.asType();
                        TypeName typeName = TypeName.get(typeMirror);
                        if(typeName instanceof ParameterizedTypeName){
                            typeName=((ParameterizedTypeName) typeName).rawType;
                        }
                    }else{
                        logger.error("Schama 必须使用在Class上");
                    }
                }
                JavaFile file=JavaFile.builder(Consts.GENERATE_FILE_PACKAGE_NAME,typeBuilder.build())
                        .build();
                file.writeTo(filer);
                logger.info("生成代码完成");
            } catch (IOException e) {
                logger.error(e.getMessage());
            }
        }
    }
}
