package open.cklan.com.compile.processor;

import com.example.Priority;
import com.example.Schema;
import com.example.bean.CategoryItem;
import com.google.auto.service.AutoService;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import org.apache.commons.collections4.CollectionUtils;

import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;

import open.cklan.com.compile.util.Consts;
import open.cklan.com.compile.util.Logger;

@AutoService(Processor.class)
@SupportedSourceVersion(SourceVersion.RELEASE_7)
public class SchemaProcessor extends AbstractProcessor{
    Logger logger;
    Filer filer;
    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        logger=new Logger(processingEnv.getMessager());
        filer=processingEnv.getFiler();
        logger.info("SchemaProcessor init");
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        Set<String> supportAnnotationTypes=new LinkedHashSet<>();
        supportAnnotationTypes.add(Schema.class.getName());
        return supportAnnotationTypes;
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        logger.info("解析schema注解");
        if(!CollectionUtils.isEmpty(annotations)){
            handleSchema(roundEnv);
            logger.info("结束我的表演");
            return true;
        }
        return false;
    }

    private void handleSchema(RoundEnvironment roundEnv) {
        Set<? extends Element> schemaElements = roundEnv.getElementsAnnotatedWith(Schema.class);
        if(!CollectionUtils.isEmpty(schemaElements)){
            try {
                TypeSpec.Builder typeBuilder=TypeSpec.classBuilder(Consts.SCHEMA_HELPER_NAME)
                        .addModifiers(Modifier.PUBLIC)
                        .addModifiers(Modifier.FINAL)
                        .addJavadoc("Author wqnmlgbe,Generated by $S",this.getClass().getSimpleName());

                MethodSpec.Builder methodBuilder=MethodSpec.methodBuilder("initCategoryData")
                        .addModifiers(Modifier.PUBLIC)
                        .addModifiers(Modifier.FINAL)
                        .addModifiers(Modifier.STATIC)
                        .returns(ParameterizedTypeName.get(List.class,CategoryItem.class));
                methodBuilder.addStatement("$T<$T> categoryList=new $T()",List.class, CategoryItem.class, ArrayList.class);
                methodBuilder.addStatement("$T categoryItem =null",CategoryItem.class);
                for (Element element :schemaElements) {
                    if(element.getKind()== ElementKind.CLASS){
                        TypeMirror typeMirror = element.asType();
                        TypeName typeName = TypeName.get(typeMirror);
                        Schema schema=element.getAnnotation(Schema.class);
                        String name=schema.name();
                        Priority priority=schema.priority();
                        methodBuilder.addStatement("categoryItem =new $T()",CategoryItem.class);
                        methodBuilder.addStatement("categoryItem.name=$S",name);
                        methodBuilder.addStatement("categoryItem.className=$S",typeName);
                        if(priority==Priority.HIGH){
                            methodBuilder.addStatement("categoryList.add(0,categoryItem)");
                        }else{
                            methodBuilder.addStatement("categoryList.add(categoryItem)");
                        }
                    }else{
                        logger.error(Schema.class.getSimpleName()+"必须使用在Activity上");
                    }
                }
                methodBuilder.addStatement("return categoryList");
                typeBuilder.addMethod(methodBuilder.build());
                JavaFile file=JavaFile.builder(Consts.GENERATE_FILE_PACKAGE_NAME,typeBuilder.build())
                        .build();
                file.writeTo(filer);
                logger.info("生成代码完成");
            } catch (IOException e) {
                logger.error(e.getMessage());
            }
        }
    }
}
